#!/bin/bash
CONTAINER_ID=$1
echo "container: $CONTAINER_ID"
CMD=$2

if [[ "$CMD" == 'test' ]]; then
  docker exec -it $CONTAINER_ID python client.py "${@:2}" --dim=$DIM
else
  echo $CMD
  docker exec -it $CONTAINER_ID python client.py "${@:2}"
fi
